### ISSUE TITLE
Automate service instance creation

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/btp-user-management-microservice#5]
Hello @ale-biagi,

thank you for sharing this example. I think it could be improved by automatically creating the service instances. Currently you give instructions on how [Create the Required Service Instances](https://github.com/SAP-samples/btp-user-management-microservice#create-the-required-service-instances). But you might check my bookshop-demo project where I e.g. create an instance for the [xsuaa API access](https://github.com/gregorwolf/bookshop-demo/blob/main/mta-cf.yaml#L190) using the mta.yaml.

Best Regards
Gregor

**Comment by ale-biagi** [comment]
Hello @gregorwolf,

Thanks for the feedback.

Actually, as we use this project in several partner trainings, I use the manual procedure to enforce their learning experience. Using the mta.yaml will require them to build and deploy the app before testing it locally, which I'd like them to do before deploying.

But you're right. It could be easily done automatically using the mta.yaml.

Thanks!

Best Regards,
Alessandro

**Comment by gregorwolf** [comment]
Maybe you can also show the use of mtaext files and use this example for the automated deployment.
